version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  allow:
    # Enable updates for indirect dependencies
    - dependency-type: "all"
  open-pull-requests-limit: 10
