import plugins.eightball
import plugins.links
import plugins.locations
import plugins.misc
import plugins.profile
import plugins.shitpost
import plugins.token
import plugins.tours
import plugins.translations
import plugins.usernames
