from __future__ import annotations

import json
from pathlib import Path

import pytest

from cerbottana.plugins.tcg import to_card_thumbnail


def is_errmsg(html: str) -> bool:
    """Evaluates tcg.to_card_thumbnail() output.

    Args:
        html (str): htmlbox generated by tcg.to_card_thumbnail().

    Returns:
        bool: True if tcg.to_card_thumbnail() failed to render the card.
    """
    return html.startswith("Immagine per")


@pytest.mark.parametrize(
    "layout", Path("tests/fixtures/scryfall/layouts").glob("*.json")
)
def test_thumbnail_layout(layout: Path) -> None:
    """Tests whether a card layout is rendered correctly."""
    print(f"Testing against: {layout}")
    with layout.open(encoding="utf-8") as testdata:
        card_json = json.load(testdata)
    assert not is_errmsg(str(to_card_thumbnail(card_json)))


def test_thumbnail_missing_image_uris() -> None:
    """Tests whether a card with missing image_uris triggers a fallback."""
    card_json = {
        "name": "Dummy Card Name",
        "scryfall_uri": "https://dummy.url/",
    }
    assert is_errmsg(str(to_card_thumbnail(card_json)))
