from __future__ import annotations

import glob
import json

import pytest

import plugins.tcg as tcg


def is_errmsg(html: str) -> bool:
    """Evaluates tcg.to_card_thumbnail() output.

    Args:
        html (str): htmlbox generated by tcg.to_card_thumbail().

    Returns:
        bool: True if tcg.to_card_thumbnail() failed to render the card.
    """
    return html.startswith("Immagine per")


@pytest.mark.parametrize("layout", glob.glob("tests/fixtures/scryfall/layouts/*.json"))
def test_thumbnail_layout(layout: str) -> None:
    """Tests whether a card layout is rendered correctly."""
    print(f"Testing against: {layout}")
    with open(layout) as testdata:
        card_json = json.load(testdata)
    assert not is_errmsg(tcg.to_card_thumbnail(card_json))


def test_thumbnail_missing_image_uris() -> None:
    """Tests whether a card with missing image_uris triggers a fallback."""
    card_json: tcg.JsonDict = {
        "name": "Dummy Card Name",
        "scryfall_uri": "https://dummy.url/",
    }
    assert is_errmsg(tcg.to_card_thumbnail(card_json))
