name: main

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Check import order
      run: isort --check .
    - name: Check formatting using black
      run: black --check .
    - name: Check docstrings with darglint
      run: find . -name '*.py' -not -path './.*' | xargs darglint -v 2
    - name: Test with mypy
      run: mypy .
    - name: Test with pylint
      run: find . -name '*.py' -not -path './.*' | xargs pylint --disable=fixme
    - name: Test with pytest
      run: pytest --cov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        fail_ci_if_error: true
