name: main

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.9
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache Poetry virtualenv
      id: virtualenv-cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: poetry-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ steps.setup-python.outputs.python-version }}-
    - name: Cache veekun database
      id: veekun-cache
      uses: actions/cache@v2
      with:
        path: veekun.sqlite
        key: veekun-${{ hashFiles('data/veekun/*.csv', 'databases/veekun.py', 'tasks/veekun.py') }}
    - name: Install Poetry
      run: pipx install poetry
    - name: Setup the virtual environment
      run: |
        poetry config --local virtualenvs.in-project true
        poetry env use $(which python)
    - name: Install dependencies on a cache miss...
      if: steps.virtualenv-cache.outputs.cache-hit != 'true'
      run: make deps
    - name: ...or mark them as up-to-date on a cache hit
      if: steps.virtualenv-cache.outputs.cache-hit == 'true'
      run: make deps --touch
    - name: Mark the veekun database as up-to-date on a cache hit
      if: steps.veekun-cache.outputs.cache-hit == 'true'
      run: sqlite3 veekun.sqlite "UPDATE latest_commit SET commit_id = '$GITHUB_SHA';"
    - name: Check import order
      run: make isort_check
    - name: Check formatting using black
      run: make black_check
    - name: Check docstrings with darglint
      run: make darglint
    - name: Test with mypy
      run: make mypy
    - name: Test with pylint
      run: make pylint
    - name: Test with pytest
      run: make pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
