name: main

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9
    - name: Install Poetry
      run: |
        curl -fsS https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - -y
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Check import order
      run: make isort_check
    - name: Check formatting using black
      run: make black_check
    - name: Check docstrings with darglint
      run: make darglint
    - name: Test with mypy
      run: make mypy
    - name: Test with pylint
      run: make pylint
    - name: Test with pytest
      run: make pytest
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@1fc7722ded4708880a5aea49f2bfafb9336f0c8d
      with:
        fail_ci_if_error: true
