name: update-veekun-data

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: cerbottana
      - name: Clone veekun pokedex
        uses: actions/checkout@v4
        with:
          repository: veekun/pokedex
          path: veekun
      - name: Update veekun data
        run: cp veekun/pokedex/data/csv/*.csv cerbottana/cerbottana/data/veekun/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          path: cerbottana
          token: ${{ secrets.MACHINE_USER_PAT }}
          push-to-fork: prnss/cerbottana
          commit-message: "Veekun: update data"
          title: "Veekun: update data"
          branch: veekun-update-data
