on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: cerbottana
    - name: Clone veekun pokedex
      uses: actions/checkout@v2
      with:
        repository: veekun/pokedex
        path: veekun
    - name: Update veekun data
      run: cp veekun/pokedex/data/csv/*.csv cerbottana/data/veekun/
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@c7f493a8000b8aeb17a1332e326ba76b57cb83eb
      with:
        path: cerbottana
        commit-message: 'Veekun: update data'
        title: 'Veekun: update data'
        branch: veekun-update-data
