on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt
    - name: Update username colors
      run: |
        cd scripts
        python update-custom-username-colors.py
        black utils.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        path: cerbottana
        commit-message: 'Update custom username colors'
        title: 'Update custom username colors'
        branch: update-custom-username-colors
